name: CI/CD for Flask App
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and Push Docker Image
      run: |
        docker build -t minhajms/my-first-docker-image:latest .
        docker push minhajms/my-first-docker-image:latest
    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_PEM_KEY }}" > docker1.pem
        chmod 400 "docker1.pem"
    - name: Deploy on EC2
      run: |
        ssh -i "docker1.pem" ubuntu@ec2-51-21-2-45.eu-north-1.compute.amazonaws.com
        docker pull minhajms/my-first-docker-image:latest
        docker stop flask-app || true
        docker rm flask-app || true
        docker run -d --name flask-app -p 8000:8000 minhajms/my-first-docker-image:latest
        EOF (edited) 









